# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-ingress-operator:operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - services
  verbs:
  - create
  - list
  - watch

- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  verbs:
  - "*"

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch

- apiGroups:
  - ingress.openshift.io
  resources:
  - clusteringresses
  verbs:
  - list
  - watch

- apiGroups:
  - operatorstatus.openshift.io
  resources:
  - operatorstatuses
  verbs:
  - create
  - get
  - update

- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - namespaces
  verbs:
  - list
  - watch
# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  - subjectaccessreviews
  verbs:
  - create
# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - route.openshift.io
  - ""
  resources:
  - routes
  verbs:
  - list
  - watch
# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - route.openshift.io
  - ""
  resources:
  - routes/status
  verbs:
  - update
