apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ingress
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cloud-credentials
    namespace: openshift-ingress-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:CreateSecurityGroup
      - ec2:CreateTags
      - ec2:DeleteSecurityGroup
      - ec2:DescribeInstances
      - ec2:DescribeRouteTables
      - ec2:DescribeSecurityGroups
      - ec2:DescribeSubnets
      - ec2:DescribeVpcs
      - ec2:RevokeSecurityGroupIngress
      - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
      - elasticloadbalancing:AttachLoadBalancerToSubnets
      - elasticloadbalancing:ConfigureHealthCheck
      - elasticloadbalancing:CreateLoadBalancer
      - elasticloadbalancing:CreateLoadBalancerListeners
      - elasticloadbalancing:CreateLoadBalancerPolicy
      - elasticloadbalancing:DeleteLoadBalancer
      - elasticloadbalancing:DeleteLoadBalancerListeners
      - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
      - elasticloadbalancing:DescribeLoadBalancerAttributes
      - elasticloadbalancing:DescribeLoadBalancers
      - elasticloadbalancing:DetachLoadBalancerFromSubnets
      - elasticloadbalancing:ModifyLoadBalancerAttributes
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer
      - route53:ListHostedZones
      - route53:ChangeResourceRecordSets
      - tag:GetResources
      resource: "*"
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ingress-azure
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cloud-credentials
    namespace: openshift-ingress-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
    - role: Contributor
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ingress-gcp
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cloud-credentials
    namespace: openshift-ingress-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - roles/dns.admin
